### PR TITLE
The merger does not conflict changes from other forks.

### PR DESCRIPTION
**Pull request by Moro4125**

### CODE REVIEW

**Comment by glensc** [comment]
you should rebase with upstream master and push -f

you seem to have lots of other commits in same branch that you created PR with (Moro4125:master)

**Comment by glensc** [comment]
i believe the commands you need to do are:
```
git checkout master
git fetch git@github.com:RobLoach/component-installer.git
git rebase -i FETCH_HEAD
git push -f
```
and AFTER this PR has been merged, you should reset **your** master to be equal to upstream master:

```
git checkout master
git fetch git@github.com:RobLoach/component-installer.git
git reset --hard FETCH_HEAD
```

and next time if you create PR, **always** create feature branch, do not commit to master!

**Comment by Moro4125** [comment]
Thank you. I create new branch "feature-changes-from-forks". And I try to create PR again

**Comment by glensc** [comment]
this was exacly why i wrote here that you **would not create new pr**

**Pull request closed without merging**
